[package]
name = "etude"
version = "1.1.0"
description = "画谱桌面应用"
authors = ["Etude"]
edition = "2021"
default-run = "etude"

[[bin]]
name = "etude"
path = "src/main.rs"

[[bin]]
name = "Uninstall"
path = "src/bin/uninstaller.rs"

[lib]
name = "etude_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rdev = "0.5.3"
windows = { version = "0.62.2", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_Input_KeyboardAndMouse"] }
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-dialog = "2.7.2"
once_cell = "1"
image = { version = "0.25", default-features = false, features = ["bmp", "jpeg", "png", "webp"] }
tokio = { version = "1", features = ["sync"] }
rusqlite = { version = "0.32", features = ["bundled"] }
