[package]
name = "etude_installer"
version = "0.1.2"
description = "画谱极简安装向导"
authors = ["Etude"]
edition = "2021"

[lib]
name = "etude_installer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
